src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Models/SurveyViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ITechArt.Surveys.WebApp.Models
{
    public class SurveyViewModel
    {
        [Required(ErrorMessage = "Set survey name")]
        [MinLength(2, ErrorMessage = "Name should contain 2-256 characters")]
        [MaxLength(256, ErrorMessage = "Name should contain 2-256 characters")]
        [DisplayName("Name")]
        public string Name { get; set; }

        public List<QuestionViewModel> Questions { get; set; }
    }
}

src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Controllers/SurveyController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ITechArt.Surveys.DomainModel;
using ITechArt.Surveys.Foundation.Interfaces;
using ITechArt.Surveys.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace ITechArt.Surveys.WebApp.Controllers
{
    public class SurveyController : Controller
    {
        private readonly ISurveyService _surveyService;


        public SurveyController(ISurveyService surveyService)
        {
            _surveyService = surveyService;
        }


        [HttpGet]
        public IActionResult CreateSurvey()
        {
            var model = new SurveyViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateSurvey(SurveyViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var questions = model.Questions.Select(q => new Question
                {
                    Title = q.Title,
                    Order = q.Index
                })
                .ToList();

            var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var survey = new Survey
            {
                Name = model.Name,
                CreatedById = currentUserId,
                CreationDate = DateTime.Now,
                Questions = questions
            };

            await _surveyService.CreateAsync(survey);

            return RedirectToAction("Index", "Home");
        }
    }
}

src/ITechArt.Surveys/ITechArt.Surveys.WebApp/Views/Survey/CreateSurvey.cshtml
@model SurveyViewModel

@{
    ViewData["Title"] = "Create survey";
}

@section Scripts
{
    <script src="~/js/createSurvey.js" asp-append-version="true"></script>
}

<link rel="stylesheet" href="~/css/createSurvey.css"/>

<form asp-controller="Survey" asp-action="CreateSurvey" method="post" id="survey-form">
    <div class="survey-info">
        <div class="name">
            @Html.TextBoxFor(m => m.Name, new { placeholder = "Survey name" })
        </div>
        <div>
            Questions: <span id="questions-counter">0</span>
        </div>
    </div>
    <div class="wrapper">
        <div class="center">
            <div class="save-discard-buttons">
                <button type="submit" class="btn btn-outline-primary">Save</button>
                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-danger">Discard</a>
            </div>
            <div class="survey-content" id="survey-content">
            </div>
        </div>
        <div class="questions-menu" id="questions-menu">
            <div class="btn btn-outline-secondary" id="create-text-question">Text</div>
        </div>
    </div>
</form>